### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by galkin** [Kloudless/kloudless-node#11]
I use

- Node 10.14.1
- NPM 6.4.1

There is such message:

```
npm install kloudless
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
+ kloudless@1.0.6
updated 1 package and audited 22475 packages in 13.078s
found 8 moderate severity vulnerabilities
```

So we have two deprecated package and 8 possible vulnerabilities.

**Comment by chri-roch12** [comment]
Hey @galkin, Our engineering team has a pretty full load, but if you want to update those dependencies we'd be happy to merge those changes in. We're making significant updates to this SDK, so other major changes to it may not be worthwhile.

**Comment by chri-roch12** [comment]
I'm closing this out, as the changes have been merged in. Thanks again @galkin !

**Comment by galkin** [comment]
@chri-roch12, but you didn't publish new version with this changes.

**Comment by hong19** [comment]
@galkin Thanks your notification. The new version 1.0.7 has been published to npm.
