### ISSUE TITLE
Documentation about folders.create() mentions wrong parameter name

### ISSUE THREAD

**Issue by blarsy** [Kloudless/kloudless-node#3]
The doc about folders.create() states a 'folder_id' paramter. This creates the folder systematically in the root folder of the cloud storage.
Should be 'parent_id' (tested, and works for me)

No big deal, though :-)

**Comment by vinodc** [comment]
Thanks! Fixed in https://github.com/Kloudless/kloudless-node/commit/59b5d79b17e8245f4684a45f7b716d87f328659d
